In [44]:
from numpy import *
from numpy.random import *
from matplotlib.pyplot import *
%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (10.0, 8.0)

In [5]:
a = array( [1,2,3])
a

array([1, 2, 3])

In [6]:
b = array([2,1,3])

In [7]:
a + b

array([3, 3, 6])

In [8]:
a - b

array([-1,  1,  0])

In [9]:
a * b

array([2, 2, 9])

In [10]:
a / b


array([ 0.5,  2. ,  1. ])

In [12]:
c = arange(11.)
c

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [13]:
c = arange?


In [14]:
x = arange(0,2*pi,0.05)

In [15]:
y = sin(x)

In [25]:
plot(x,y)

In [26]:
x = linspace(0,2*pi, 50)

In [27]:
plot(sin(x))

In [48]:
plot (x, sin(x),
      x, sin(2*x))

In [33]:
plot (x, -sin(2*x),
      x/2, sin(x))


In [47]:
plot (x, -sin(2*x),'b-o',
      x/2, sin(x),'r-^')


In [46]:
scatter (x, sin(x), rand(len(x))*30,rand(len(x)))
colorbar()

In [45]:
n = 200
scatter(rand(n), rand(n), rand(n)*30,rand(n))
colorbar()


In [70]:
figure()
scatter (x, sin(x), rand(len(x))*30,rand(len(x)))
colorbar()
figure()
plot (x, sin(x),
      x, sin(2*x))


In [57]:
subplot(2,1,1)
plot (x, sin(x),
      x, sin(2*x))
subplot(2,1,2)
plot (x, -sin(x),
      x, sin(2*x))
title('titled')
xlabel('rads')
ylabel('amp',fontsize='large')
grid()
legend(['-sin(x)','sin(2*x)'])


In [71]:
from scipy.misc import lena
from matplotlib.pyplot import cm

img = lena()

cm.cmap_d

{'Accent': <matplotlib.colors.LinearSegmentedColormap at 0x7fec2246aa90>,
 'Accent_r': <matplotlib.colors.LinearSegmentedColormap at 0x7fec22463ac8>,
 'Blues': <matplotlib.colors.LinearSegmentedColormap at 0x7fec22463208>,
 'Blues_r': <matplotlib.colors.LinearSegmentedColormap at 0x7fec2246a0b8>,
 'BrBG': <matplotlib.colors.LinearSegmentedColormap at 0x7fec22463d68>,
 'BrBG_r': <matplotlib.colors.LinearSegmentedColormap at 0x7fec2246a3c8>,
 'BuGn': <matplotlib.colors.LinearSegmentedColormap at 0x7fec22463b00>,
 'BuGn_r': <matplotlib.colors.LinearSegmentedColormap at 0x7fec2246a438>,
 'BuPu': <matplotlib.colors.LinearSegmentedColormap at 0x7fec22463ba8>,
 'BuPu_r': <matplotlib.colors.LinearSegmentedColormap at 0x7fec22463518>,
 'CMRmap': <matplotlib.colors.LinearSegmentedColormap at 0x7fec22463ef0>,
 'CMRmap_r': <matplotlib.colors.LinearSegmentedColormap at 0x7fec2246a1d0>,
 'Dark2': <matplotlib.colors.LinearSegmentedColormap at 0x7fec2246a2b0>,
 'Dark2_r': <matplotlib.colors.LinearSegm

In [73]:
imshow(img,cmap=cm.Purples_r)
colorbar()


In [74]:
0

0